version: '2'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    container_name: zk
  kafka:
    image: wurstmeister/kafka:1.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.6.5.151
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://0.0.0.0:9092
    container_name: kafka
    links:
      - zookeeper
    volumes:
      - .:/mnt
